name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to AWS S3
        run: |
          aws s3 sync .//Users/mollyfrost/Desktop/School/92A\&M_Fall_2023/412_Cloud_Computing/CSCE412-Project3 s3://cs412mfrost.xyz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAYTLS2MGSBSTKV4WK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEK7srpe3HRnhtMu3fWAl16hlAEcsrlWBxRNCSpX }}
